### PR TITLE
Upgrade version to v19.12

### PR DESCRIPTION
**Pull request by seladb**

### CODE REVIEW

**Comment by uilianries** [comment]
Hi @seladb I gonna create a new branch to pull your changes. BTW, are you interested in move this recipe to Conan Center Index? We can help you.

**Comment by seladb** [comment]
thanks for the quick response @uilianries. Why is a new branch needed? Do you mean a stable branch to publish the new version to Bintray?

Regarding Conan Center Index - I'm not sure what is. Can you elaborate?

**Comment by uilianries** [comment]
@seladb take a look on the blog post about [Conan Center Index](https://blog.conan.io/2019/09/04/A-new-binary-building-service-for-Conan-center-packages.html).

We are moving Bincrafters and Conan Community recipes to CCI. So the idea is opening a PR with a new recipe to CCI, which will became the official one.

**Comment by ericLemanissier** [comment]
pcapplusplus requires libpcap, which requires libusb, bison_installer and flex_installer, so there is some migration to do beforehand

**Comment by seladb** [comment]
Sure, I'm open to move to CCI. Please let me know when pcapplusplus dependencies are resolved

**Comment by uilianries** [comment]
@ericLemanissier I forgot about the others!

**Review by Croydon — APPROVED** [review]
LGTM

**Comment by seladb** [comment]
Thanks for merging the PR! will you take of uploading it to bintray?

**Comment by Croydon** [comment]
When the `testing/` branch succeeds, we will create a `stable/` branch, which will upload all builds.

**Comment by seladb** [comment]
awesome, thanks!

**Comment by seladb** [comment]
btw, does it mean that you'll wait for libpcap and the other dependencies to work on all platforms before uploading the new pcapplusplus version to bintray?

**Comment by ericLemanissier** [comment]
that's what we usually do. Visual studio already passed https://ci.appveyor.com/project/bincrafters/conan-pcapplusplus/builds/29374410 and travis should pass too, now that https://github.com/bincrafters/conan-libpcap/pull/2 is merged

**Comment by seladb** [comment]
I just received an email that the package has been uploaded to bintray: https://bintray.com/bincrafters/public-conan/pcapplusplus%3Abincrafters/19.12%3Astable

Thank you so much for your help!

**Comment by Croydon** [comment]
Thank you for contributing! 😄

**Pull request merged**
